### ISSUE TITLE
Create ticket with attachments issue

### ISSUE THREAD

**Issue by Itay4** [CZ-NIC/python-rt#21] opened 2018-07-12 12:39 UTC
When running the following code:
```
attachment_content = b'Content of attachment.'
attachment_name = 'attachment-name.txt'
tracker.create_ticket(files=[(attachment_name, attachment_content, 'text/plain')])
```
Getting the following error:
```
   File "/usr/local/lib/python2.7/site-packages/rt.py", line 630, in create_ticket
    msg = self.__request('ticket/new', post_data={'content': post_data})
   File "/usr/local/lib/python2.7/site-packages/rt.py", line 268, in __request
    self.__check_response(result)
   File "/usr/local/lib/python2.7/site-packages/rt.py", line 303, in __check_response
    raise APISyntaxError(msg[2][2:] if len(msg) > 2 else 'Syntax error.')
 APISyntaxError: Could not create ticket.
```
Any help is appreciated.

**Comment by wagner-certat** [comment] 2018-07-12 13:17
The second parameter needs to be a file-like object

**Comment by wagner-certat** [comment] 2018-07-12 13:43
```
import io
attachment = io.BytesIO(b'Content of attachment')
# create your ticket here
```

**Comment by Itay4** [comment] 2018-07-12 13:48
Tried to run:
```
attachment_name = 'attachment-name.txt'
attachment = io.BytesIO(b'Content of attachment')
tracker.create_ticket(files=[(attachment_name, attachment, 'text/plain')])
```
Still getting the same error, what am I doing wrong?

**Comment by wagner-certat** [comment] 2018-07-12 14:20
Which RT version are you using?

I send the attachments with the reply function: https://github.com/certat/intelmq/blob/master/intelmq/bin/intelmqcli.py#L437

Don't you need to specify queue and subject and so on?

**Comment by Itay4** [comment] 2018-07-12 14:36
@wagner-certat 
Using RT version 4.4.2
I would like to add the attachment to a ticket, not send it.
Not for a specific queue or subject, just trying generally to add an attachment.

**Comment by wagner-certat** [comment] 2018-07-13 07:17
Works for me (with and without PR #20 applied):

```
tracker = rt.Rt('http://demo.request-tracker.fr/REST/1.0')
tracker.login(login='administrateur', password='administrateur')  # returns True
attachment_name = 'attachment-name.txt'
attachment = io.BytesIO(b'Content of attachment')
tracker.create_ticket(files=[(attachment_name, attachment, 'text/plain')])  # returns 273
```

**Comment by wagner-certat** [comment] 2018-07-13 10:35
>  By the way, I suggest releasing the current master.

ping @e3rd

**Comment by e3rd** [comment] 2018-07-14 11:34
Sorry for the delay. I've just pushed a new release here on Github... but did you mean to release here on Github or on Pypi or where?

**Comment by Itay4** [comment] 2018-07-14 11:58
@e3rd Thanks for the release.
I actually meant releasing here on git, but I guess Pypi would be a good idea as well.

**Comment by e3rd** [comment] 2018-07-14 20:49
I admit it was somebody else who released 1.0.10 version in Dec on PyPi – so that the version 1.0.10 here and on PyPi differs – the version here is few commits ahead. I'll try to keep that in mind and do the next release both on PyPi and here in the same time as soon as several commits will appear in the master.

**Comment by wagner-certat** [comment] 2018-07-15 06:39
> I admit it was somebody else who released 1.0.10 version in Dec on PyPi – so that the version 1.0.10 here and on PyPi differs – the version here is few commits ahead.

I recommend to do one release that fixes the difference. Even if the only change is that both versions are now in line with each other (which is a bugfix, but the bug was not in the code).

**Comment by e3rd** [comment] 2018-07-16 12:54
Okay, thanks, there is now a reformatted version, 1.0.11 on both channels.

**Comment by wagner-certat** [comment] 2018-07-17 13:06
@Itay4 if the problem is solved, please close this issue

**Closed** 2018-07-17 13:24 UTC
